### PR TITLE
Observability grafana dashboard

### LINKED ISSUE #11: Scripting grafana dashboards
Create some interesting visualizations of ChRIS data e.g.

image

Figure out how to automatically add these dashboards to Grafana when the project is brought up by `docker compose up -d` (or as a `docker compose run` command fired by `./minichris.sh`

### PR DESCRIPTION
**Pull request by mdsahiloss**
Fixes #11 

Adds PostgreSQL as datasource of grafana

### CODE REVIEW

**Comment by mdsahiloss** [comment]
@jennydaman I've added PostgresSQL as datasource and now PostgreSQL gets attached to grafana at runtime of `docker compose up`  but querying to postgres giving me an error :
```
db query error: pq: SSL is not enabled on the server
```
Which is SSL enablity issue, Should I make changes to `chris_db` image configuration in docker-compose file?

**Comment by jennydaman** [comment]
@MdSahil-oss looking good so far.

https://grafana.com/docs/grafana/latest/datasources/postgres/#provision-the-data-source

From the example, it seems like adding `sslmode: 'disable'` is a good solution.

Would you remove the `PostgresChrisStoreDB` datasource? (The ChRIS project is being restructured and in our timeline we are planning to remove the ChRIS Store).

**Comment by jennydaman** [comment]
@MdSahil-oss I moved everything grafana-related to a directory called grafana.

What is the purpose of `provisioning/dashboards/automatic.yml`? Seems to work without it.

**Comment by mdsahiloss** [comment]
@jennydaman The purpose of `provisioning/dashboards/automatic.yml` to provide dashboards at start time of grafana. grafana is  working the same without `provisioning/dashboards/automatic.yml` because I haven't configured any dashboard yet but very soon  I'll configure dashboards for:
- most popular plugins of all time
- plugin instances created per week, showing what state they're in (e.g. finishedSuccessfully, finishedWithError, cancelled)

**Comment by mdsahiloss** [comment]
@jennydaman I have a question for Dashboard `most popular plugins of all time`, how to find popularity of a particular plugin ?
means what are that factors on which popularity of a plugin will depend ?

**Comment by mdsahiloss** [comment]
@jennydaman I've added dashboards but I'm not able to debug them, lacking of plugins related data. Please let me know whether dashboards are working fine of not.

**Pull request closed without merging**
